# Generated by Django 4.0.4 on 2022-06-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myimdb_watchlist', '0003_streamplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myimdb_watchlist.streamplatform'),
        ),
    ]
